# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_new_table.ui'
#
# Created: Mon Jul  2 23:49:15 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(820, 599)
        Dialog.setMinimumSize(QtCore.QSize(820, 599))
        Dialog.setMaximumSize(QtCore.QSize(820, 599))
        Dialog.setWindowOpacity(1.0)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(460, 540, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.listView = QtGui.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(540, 30, 256, 192))
        self.listView.setObjectName(_fromUtf8("listView"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 114, 281))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.line_radio = QtGui.QRadioButton(self.groupBox)
        self.line_radio.setObjectName(_fromUtf8("line_radio"))
        self.buttonGroup = QtGui.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.line_radio)
        self.verticalLayout.addWidget(self.line_radio)
        self.choice_radio = QtGui.QRadioButton(self.groupBox)
        self.choice_radio.setObjectName(_fromUtf8("choice_radio"))
        self.buttonGroup.addButton(self.choice_radio)
        self.verticalLayout.addWidget(self.choice_radio)
        self.num_radio = QtGui.QRadioButton(self.groupBox)
        self.num_radio.setObjectName(_fromUtf8("num_radio"))
        self.buttonGroup.addButton(self.num_radio)
        self.verticalLayout.addWidget(self.num_radio)
        self.date_radio = QtGui.QRadioButton(self.groupBox)
        self.date_radio.setObjectName(_fromUtf8("date_radio"))
        self.buttonGroup.addButton(self.date_radio)
        self.verticalLayout.addWidget(self.date_radio)
        self.time_radio = QtGui.QRadioButton(self.groupBox)
        self.time_radio.setObjectName(_fromUtf8("time_radio"))
        self.buttonGroup.addButton(self.time_radio)
        self.verticalLayout.addWidget(self.time_radio)
        self.grp_radio = QtGui.QRadioButton(self.groupBox)
        self.grp_radio.setObjectName(_fromUtf8("grp_radio"))
        self.buttonGroup.addButton(self.grp_radio)
        self.verticalLayout.addWidget(self.grp_radio)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(140, 10, 381, 581))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.txt_group = QtGui.QGroupBox(self.tab_3)
        self.txt_group.setGeometry(QtCore.QRect(10, 10, 361, 531))
        self.txt_group.setObjectName(_fromUtf8("txt_group"))
        self.gridLayout = QtGui.QGridLayout(self.txt_group)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEdit = QtGui.QLineEdit(self.txt_group)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.txt_group)
        self.checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.txt_group)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.txt_group)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.txt_group)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(100000)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout.addWidget(self.spinBox, 1, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.txt_group)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.choice_group = QtGui.QGroupBox(self.tab_4)
        self.choice_group.setGeometry(QtCore.QRect(10, 10, 361, 531))
        self.choice_group.setObjectName(_fromUtf8("choice_group"))
        self.gridLayout_2 = QtGui.QGridLayout(self.choice_group)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEdit_2 = QtGui.QLineEdit(self.choice_group)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_2.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 1, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.choice_group)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout_2.addWidget(self.textEdit, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.choice_group)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.choice_group)
        self.checkBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_2.addWidget(self.checkBox_2, 0, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.choice_group)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.choice_group)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_2.addWidget(self.pushButton_2, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.num_group = QtGui.QGroupBox(self.tab_7)
        self.num_group.setGeometry(QtCore.QRect(10, 10, 361, 531))
        self.num_group.setObjectName(_fromUtf8("num_group"))
        self.gridLayout_3 = QtGui.QGridLayout(self.num_group)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lineEdit_3 = QtGui.QLineEdit(self.num_group)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_3.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.num_group)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.num_group)
        self.checkBox_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout_3.addWidget(self.checkBox_3, 0, 2, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.num_group)
        self.spinBox_2.setMaximum(999999998)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout_3.addWidget(self.spinBox_2, 1, 1, 1, 1)
        self.spinBox_3 = QtGui.QSpinBox(self.num_group)
        self.spinBox_3.setMaximum(999999999)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.gridLayout_3.addWidget(self.spinBox_3, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.num_group)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.num_group)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.num_group)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_3.addWidget(self.pushButton_3, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 351, 531))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 351, 531))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 10, 351, 531))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.buttonGroup, QtCore.SIGNAL(_fromUtf8("buttonClicked(int)")), Dialog.changeFieldDescriptions)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.acceptFieldAdd)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.acceptFieldAdd)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.line_radio, self.choice_radio)
        Dialog.setTabOrder(self.choice_radio, self.num_radio)
        Dialog.setTabOrder(self.num_radio, self.date_radio)
        Dialog.setTabOrder(self.date_radio, self.time_radio)
        Dialog.setTabOrder(self.time_radio, self.grp_radio)
        Dialog.setTabOrder(self.grp_radio, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.buttonBox)
        Dialog.setTabOrder(self.buttonBox, self.listView)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Field Types", None, QtGui.QApplication.UnicodeUTF8))
        self.line_radio.setText(QtGui.QApplication.translate("Dialog", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.choice_radio.setText(QtGui.QApplication.translate("Dialog", "Choice", None, QtGui.QApplication.UnicodeUTF8))
        self.num_radio.setText(QtGui.QApplication.translate("Dialog", "Number", None, QtGui.QApplication.UnicodeUTF8))
        self.date_radio.setText(QtGui.QApplication.translate("Dialog", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.time_radio.setText(QtGui.QApplication.translate("Dialog", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_radio.setText(QtGui.QApplication.translate("Dialog", "Person/Group", None, QtGui.QApplication.UnicodeUTF8))
        self.txt_group.setTitle(QtGui.QApplication.translate("Dialog", "Field Description", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Dialog", "Unique:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Row Name: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Dialog", "Add >>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Dialog", "Page", None, QtGui.QApplication.UnicodeUTF8))
        self.choice_group.setTitle(QtGui.QApplication.translate("Dialog", "Field Description", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit.setToolTip(QtGui.QApplication.translate("Dialog", "Enter each choice on a newline.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Row Name: ", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("Dialog", "Unique:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Choices:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("Dialog", "Add >>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("Dialog", "Page", None, QtGui.QApplication.UnicodeUTF8))
        self.num_group.setTitle(QtGui.QApplication.translate("Dialog", "Field Description", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Row Name: ", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("Dialog", "Unique:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "From:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "To:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("Dialog", "Add >>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QtGui.QApplication.translate("Dialog", "Page", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Dialog", "Field Description", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("Dialog", "Page", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Dialog", "Field Description", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("Dialog", "Page", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("Dialog", "Field Description", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))

