# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_new_table.ui'
#
# Created: Sat Jul  7 15:44:52 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(820, 599)
        Dialog.setMinimumSize(QtCore.QSize(820, 599))
        Dialog.setMaximumSize(QtCore.QSize(820, 599))
        Dialog.setWindowOpacity(1.0)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(460, 540, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.list_db_rows = QtGui.QListWidget(Dialog)
        self.list_db_rows.setGeometry(QtCore.QRect(540, 110, 256, 192))
        self.list_db_rows.setObjectName(_fromUtf8("list_db_rows"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 114, 281))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.line_radio = QtGui.QRadioButton(self.groupBox)
        self.line_radio.setChecked(True)
        self.line_radio.setObjectName(_fromUtf8("line_radio"))
        self.buttonGroup = QtGui.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.line_radio)
        self.verticalLayout.addWidget(self.line_radio)
        self.choice_radio = QtGui.QRadioButton(self.groupBox)
        self.choice_radio.setObjectName(_fromUtf8("choice_radio"))
        self.buttonGroup.addButton(self.choice_radio)
        self.verticalLayout.addWidget(self.choice_radio)
        self.date_radio = QtGui.QRadioButton(self.groupBox)
        self.date_radio.setObjectName(_fromUtf8("date_radio"))
        self.buttonGroup.addButton(self.date_radio)
        self.verticalLayout.addWidget(self.date_radio)
        self.time_radio = QtGui.QRadioButton(self.groupBox)
        self.time_radio.setObjectName(_fromUtf8("time_radio"))
        self.buttonGroup.addButton(self.time_radio)
        self.verticalLayout.addWidget(self.time_radio)
        self.grp_radio = QtGui.QRadioButton(self.groupBox)
        self.grp_radio.setObjectName(_fromUtf8("grp_radio"))
        self.buttonGroup.addButton(self.grp_radio)
        self.verticalLayout.addWidget(self.grp_radio)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(140, 10, 381, 581))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.txt_group = QtGui.QGroupBox(self.tab_3)
        self.txt_group.setGeometry(QtCore.QRect(10, 10, 361, 531))
        self.txt_group.setObjectName(_fromUtf8("txt_group"))
        self.gridLayout = QtGui.QGridLayout(self.txt_group)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.txt_grp_rowname = QtGui.QLineEdit(self.txt_group)
        self.txt_grp_rowname.setObjectName(_fromUtf8("txt_grp_rowname"))
        self.gridLayout.addWidget(self.txt_grp_rowname, 0, 1, 1, 1)
        self.txt_grp_unique = QtGui.QCheckBox(self.txt_group)
        self.txt_grp_unique.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.txt_grp_unique.setObjectName(_fromUtf8("txt_grp_unique"))
        self.gridLayout.addWidget(self.txt_grp_unique, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.txt_group)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.txt_group)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.txt_grp_length = QtGui.QSpinBox(self.txt_group)
        self.txt_grp_length.setMinimum(1)
        self.txt_grp_length.setMaximum(100000)
        self.txt_grp_length.setProperty("value", 255)
        self.txt_grp_length.setObjectName(_fromUtf8("txt_grp_length"))
        self.gridLayout.addWidget(self.txt_grp_length, 1, 1, 1, 1)
        self.btn_txt_group = QtGui.QPushButton(self.txt_group)
        self.btn_txt_group.setObjectName(_fromUtf8("btn_txt_group"))
        self.gridLayout.addWidget(self.btn_txt_group, 3, 2, 1, 1)
        self.txt_grp_isnull = QtGui.QCheckBox(self.txt_group)
        self.txt_grp_isnull.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.txt_grp_isnull.setObjectName(_fromUtf8("txt_grp_isnull"))
        self.gridLayout.addWidget(self.txt_grp_isnull, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.choice_group = QtGui.QGroupBox(self.tab_4)
        self.choice_group.setGeometry(QtCore.QRect(10, 10, 361, 531))
        self.choice_group.setObjectName(_fromUtf8("choice_group"))
        self.gridLayout_2 = QtGui.QGridLayout(self.choice_group)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 1, 1, 1)
        self.choice_grp_rowname = QtGui.QLineEdit(self.choice_group)
        self.choice_grp_rowname.setObjectName(_fromUtf8("choice_grp_rowname"))
        self.gridLayout_2.addWidget(self.choice_grp_rowname, 0, 1, 1, 1)
        self.choice_grp_choices = QtGui.QTextEdit(self.choice_group)
        self.choice_grp_choices.setObjectName(_fromUtf8("choice_grp_choices"))
        self.gridLayout_2.addWidget(self.choice_grp_choices, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.choice_group)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.choice_grp_unique = QtGui.QCheckBox(self.choice_group)
        self.choice_grp_unique.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.choice_grp_unique.setObjectName(_fromUtf8("choice_grp_unique"))
        self.gridLayout_2.addWidget(self.choice_grp_unique, 0, 3, 1, 1)
        self.btn_choice_group = QtGui.QPushButton(self.choice_group)
        self.btn_choice_group.setObjectName(_fromUtf8("btn_choice_group"))
        self.gridLayout_2.addWidget(self.btn_choice_group, 3, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.choice_group)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.choice_grp_isnull = QtGui.QCheckBox(self.choice_group)
        self.choice_grp_isnull.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.choice_grp_isnull.setObjectName(_fromUtf8("choice_grp_isnull"))
        self.gridLayout_2.addWidget(self.choice_grp_isnull, 1, 3, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.date_group = QtGui.QGroupBox(self.tab_5)
        self.date_group.setGeometry(QtCore.QRect(10, 10, 361, 531))
        self.date_group.setObjectName(_fromUtf8("date_group"))
        self.gridLayout_4 = QtGui.QGridLayout(self.date_group)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 2, 1, 1, 1)
        self.date_grp_unique = QtGui.QCheckBox(self.date_group)
        self.date_grp_unique.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.date_grp_unique.setObjectName(_fromUtf8("date_grp_unique"))
        self.gridLayout_4.addWidget(self.date_grp_unique, 0, 2, 1, 1)
        self.date_grp_rowname = QtGui.QLineEdit(self.date_group)
        self.date_grp_rowname.setObjectName(_fromUtf8("date_grp_rowname"))
        self.gridLayout_4.addWidget(self.date_grp_rowname, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.date_group)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.btn_date_group = QtGui.QPushButton(self.date_group)
        self.btn_date_group.setObjectName(_fromUtf8("btn_date_group"))
        self.gridLayout_4.addWidget(self.btn_date_group, 3, 2, 1, 1)
        self.date_grp_isnull = QtGui.QCheckBox(self.date_group)
        self.date_grp_isnull.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.date_grp_isnull.setObjectName(_fromUtf8("date_grp_isnull"))
        self.gridLayout_4.addWidget(self.date_grp_isnull, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.time_group = QtGui.QGroupBox(self.tab_6)
        self.time_group.setGeometry(QtCore.QRect(10, 10, 361, 531))
        self.time_group.setObjectName(_fromUtf8("time_group"))
        self.gridLayout_5 = QtGui.QGridLayout(self.time_group)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_9 = QtGui.QLabel(self.time_group)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.checkBox_5 = QtGui.QCheckBox(self.time_group)
        self.checkBox_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.gridLayout_5.addWidget(self.checkBox_5, 0, 2, 1, 1)
        self.btn_date_group_2 = QtGui.QPushButton(self.time_group)
        self.btn_date_group_2.setObjectName(_fromUtf8("btn_date_group_2"))
        self.gridLayout_5.addWidget(self.btn_date_group_2, 5, 2, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.time_group)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout_5.addWidget(self.lineEdit_5, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 4, 1, 1, 1)
        self.timeEdit_4 = QtGui.QTimeEdit(self.time_group)
        self.timeEdit_4.setObjectName(_fromUtf8("timeEdit_4"))
        self.gridLayout_5.addWidget(self.timeEdit_4, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.time_group)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 1, 0, 1, 1)
        self.timeEdit_5 = QtGui.QTimeEdit(self.time_group)
        self.timeEdit_5.setObjectName(_fromUtf8("timeEdit_5"))
        self.gridLayout_5.addWidget(self.timeEdit_5, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.time_group)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 2, 0, 1, 1)
        self.time_grp_isnull = QtGui.QCheckBox(self.time_group)
        self.time_grp_isnull.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.time_grp_isnull.setObjectName(_fromUtf8("time_grp_isnull"))
        self.gridLayout_5.addWidget(self.time_grp_isnull, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 10, 351, 531))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(540, 40, 101, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.txt_database_name = QtGui.QLineEdit(Dialog)
        self.txt_database_name.setGeometry(QtCore.QRect(650, 37, 141, 20))
        self.txt_database_name.setObjectName(_fromUtf8("txt_database_name"))
        self.txt_table_name = QtGui.QLineEdit(Dialog)
        self.txt_table_name.setGeometry(QtCore.QRect(650, 70, 141, 20))
        self.txt_table_name.setObjectName(_fromUtf8("txt_table_name"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(542, 72, 81, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label.setBuddy(self.txt_grp_rowname)
        self.label_2.setBuddy(self.txt_grp_length)
        self.label_3.setBuddy(self.choice_grp_rowname)
        self.label_4.setBuddy(self.choice_grp_choices)
        self.label_8.setBuddy(self.date_grp_rowname)
        self.label_5.setBuddy(self.txt_database_name)
        self.label_7.setBuddy(self.txt_table_name)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.buttonGroup, QtCore.SIGNAL(_fromUtf8("buttonClicked(int)")), Dialog.changeFieldDescriptions)
        QtCore.QObject.connect(self.btn_choice_group, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.acceptFieldAdd)
        QtCore.QObject.connect(self.btn_txt_group, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.acceptFieldAdd)
        QtCore.QObject.connect(self.btn_date_group_2, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.acceptFieldAdd)
        QtCore.QObject.connect(self.btn_date_group, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.acceptFieldAdd)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.line_radio, self.choice_radio)
        Dialog.setTabOrder(self.choice_radio, self.date_radio)
        Dialog.setTabOrder(self.date_radio, self.time_radio)
        Dialog.setTabOrder(self.time_radio, self.grp_radio)
        Dialog.setTabOrder(self.grp_radio, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.buttonBox)
        Dialog.setTabOrder(self.buttonBox, self.list_db_rows)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Field Types", None, QtGui.QApplication.UnicodeUTF8))
        self.line_radio.setText(QtGui.QApplication.translate("Dialog", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.choice_radio.setText(QtGui.QApplication.translate("Dialog", "Choice", None, QtGui.QApplication.UnicodeUTF8))
        self.date_radio.setText(QtGui.QApplication.translate("Dialog", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.time_radio.setText(QtGui.QApplication.translate("Dialog", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_radio.setText(QtGui.QApplication.translate("Dialog", "Person/Group", None, QtGui.QApplication.UnicodeUTF8))
        self.txt_group.setTitle(QtGui.QApplication.translate("Dialog", "Field Description - Text", None, QtGui.QApplication.UnicodeUTF8))
        self.txt_grp_unique.setText(QtGui.QApplication.translate("Dialog", "Unique?:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Row Name: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_txt_group.setText(QtGui.QApplication.translate("Dialog", "Add >>", None, QtGui.QApplication.UnicodeUTF8))
        self.txt_grp_isnull.setText(QtGui.QApplication.translate("Dialog", "Null?:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Dialog", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.choice_group.setTitle(QtGui.QApplication.translate("Dialog", "Field Description - Choice", None, QtGui.QApplication.UnicodeUTF8))
        self.choice_grp_choices.setToolTip(QtGui.QApplication.translate("Dialog", "Enter each choice on a newline.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Row Name: ", None, QtGui.QApplication.UnicodeUTF8))
        self.choice_grp_unique.setText(QtGui.QApplication.translate("Dialog", "Unique?:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_choice_group.setText(QtGui.QApplication.translate("Dialog", "Add >>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Choices:", None, QtGui.QApplication.UnicodeUTF8))
        self.choice_grp_isnull.setText(QtGui.QApplication.translate("Dialog", "Null?:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("Dialog", "Choice", None, QtGui.QApplication.UnicodeUTF8))
        self.date_group.setTitle(QtGui.QApplication.translate("Dialog", "Field Description - Date", None, QtGui.QApplication.UnicodeUTF8))
        self.date_grp_unique.setText(QtGui.QApplication.translate("Dialog", "Unique?:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Row Name: ", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_date_group.setText(QtGui.QApplication.translate("Dialog", "Add >>", None, QtGui.QApplication.UnicodeUTF8))
        self.date_grp_isnull.setText(QtGui.QApplication.translate("Dialog", "Null?:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("Dialog", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.time_group.setTitle(QtGui.QApplication.translate("Dialog", "Field Description - Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Row Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("Dialog", "Unique?:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_date_group_2.setText(QtGui.QApplication.translate("Dialog", "Add >>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Min Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Max Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.time_grp_isnull.setText(QtGui.QApplication.translate("Dialog", "Null?:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("Dialog", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("Dialog", "Field Description - Group", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Group", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Database Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Table Name:", None, QtGui.QApplication.UnicodeUTF8))

